export const Discs = [
  {
    id: 1,
    discImage: 'discs/1.jpeg',
    brand: 'Axiom',
    name: 'Hex',
    plastic: 'Neutron',
    weight: 169,
    speed: 5,
    glide: 5,
    turn: -1,
    fade: 1,
    tag: 'midrange',
  },
  {
    id: 2,
    discImage: 'discs/2.png',
    brand: 'Innova',
    name: 'Beast',
    plastic: 'Champion',
    weight: 172,
    speed: 10,
    glide: 5,
    turn: -2,
    fade: 2,
    tag: 'fairway',
  },
  {
    id: 3,
    discImage: 'discs/3.jpeg',
    brand: 'Innova',
    name: 'Orc',
    plastic: 'DX',
    weight: 172,
    speed: 10,
    glide: 4,
    turn: -1,
    fade: 3,
    tag: 'distance',
  },
  {
    id: 4,
    discImage: 'discs/4.jpeg',
    brand: 'Kastaplast',
    name: 'Falk',
    plastic: 'K1',
    weight: 180,
    speed: 9,
    glide: 6,
    turn: -2,
    fade: 2,
    tag: 'fairway'
  },
  {
    id: 5,
    discImage: 'discs/5.png',
    brand: 'Westside',
    name: 'Warship',
    plastic: 'VIP',
    weight: 180,
    speed: 6,
    glide: 5,
    turn: "0",
    fade: 1,
    tag: 'fairway',
  },
  {
    id: 6,
    discImage: 'discs/6.jpeg',
    brand: 'Discraft',
    name: 'Hades',
    plastic: 'ESP',
    weight: 180,
    speed: 12,
    glide: 6,
    turn: -3,
    fade: 2,
    tag: 'distance',
  },
  {
    id: 7,
    discImage: 'discs/7.jpeg',
    brand: 'Discraft',
    name: 'Get Freaky Zone',
    plastic: 'CryZtal Flx',
    iweight: 180,
    speed: 5,
    glide: 4,
    turn: -4,
    fade: 1,
    tag: 'putter',
  },
];
